#!/bin/bash

hostname=collabora

mkdir -p certs/ca

openssl genrsa -out certs/ca/root.key.pem 2048

openssl req -x509 -new -nodes -key certs/ca/root.key.pem -days 9131 -out certs/ca/root.crt.pem -subj "/C=CA/ST=BCN/L=Barcelona/O=Dummy Authority/CN=Dummy Authority"

mkdir -p certs/{servers,tmp}

mkdir -p "certs/servers/${hostname}"

openssl genrsa -out "certs/servers/${hostname}/privkey.pem" 2048 -key "certs/servers/${hostname}/privkey.pem"

openssl req -key "certs/servers/${hostname}/privkey.pem" -new -sha256 -out "certs/tmp/${hostname}.csr.pem" -subj "/C=CA/ST=BCN/L=Barcelona/O=Dummy Authority/CN=${hostname}"

openssl x509 -req -in certs/tmp/${hostname}.csr.pem -CA certs/ca/root.crt.pem -CAkey certs/ca/root.key.pem -CAcreateserial -out certs/servers/${hostname}/cert.pem -days 9131

mv certs/servers/${hostname}/privkey.pem ./key.pem
mv certs/servers/${hostname}/cert.pem ./cert.pem
mv certs/ca/root.crt.pem ./ca-chain.cert.pem
rm -rf ./certs
